server:
  port: 9001
spring:
  application:
    name : EMPLOYEE-SERVICE
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgresdb:5432/employee?sslmode=disable&user=postgres
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver


neo:
  openapi:
    dev-url: http://localhost:9001
    prod-url: http://ec2-34-238-117-103.compute-1.amazonaws.com:9001
