server:
  port: 9001
spring:
  application:
    name : EMPLOYEE-SERVICE
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB:postgresdb}:5432/company?sslmode=disable&user=postgres
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver


neo:
  openapi:
    dev-url: http://localhost:9001
    prod-url: ec2-54-81-208-216.compute-1.amazonaws.com:9001
