# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Employee-App CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v2


      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context:
          push: true
          tags: arbaaz1602/employeeapp:latest

      - name: Deploy to AWS EC2 server
        uses: appleboy/ssh-action@master
        with:
          host: ec2-54-167-52-216.compute-1.amazonaws.com
          username: ec2-user
          key: ${{secrets.ACTION_PRIVATE_KEY}}
          scripts: |
            docker stop ${{secrets.DOCKER_CONTAINER_NAME}}
            docker rm -f ${{secrets.DOCKER_CONTAINER_NAME}}
            docker rmi -f ${{secrets.DOCKER_REPOSITORY_IMAGE}}
            docker pull ${{secrets.DOCKER_REPOSITORY_IMAGE}}
            docker run --detach --name ${{secrets.DOCKER_CONTAINER_NAME}} -p 8080:8080 --network employeenetwork -d ${{secrets.DOCKER_REPOSITORY_IMAGE}}

